# Generated by Django 4.2.16 on 2026-04-07 17:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Insurance Agent'), ('underwriter', 'Underwriter'), ('claims_adjuster', 'Claims Adjuster'), ('admin', 'Administrator'), ('support', 'Support Staff')], default='customer', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', django_countries.fields.CountryField(default='NG', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_kyc_completed', models.BooleanField(default=False)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('policy_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('third_party', 'Third Party'), ('standalone', 'Standalone'), ('personal_accident', 'Personal Accident')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('claimed', 'Claimed')], default='pending', max_length=20)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductible', models.DecimalField(decimal_places=2, default=5000, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('additional_benefits', models.JSONField(default=list)),
                ('custom_coverage', models.JSONField(default=dict)),
                ('policy_document', models.FileField(blank=True, null=True, upload_to='policies/documents/')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance_policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('max_uses', models.IntegerField(default=1)),
                ('used_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'promo_codes',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('engine_number', models.CharField(max_length=50, unique=True)),
                ('chassis_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('bus', 'Bus'), ('rickshaw', 'Rickshaw')], max_length=20)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20)),
                ('engine_capacity', models.IntegerField(help_text='Engine capacity in CC')),
                ('color', models.CharField(max_length=50)),
                ('ownership_type', models.CharField(choices=[('single', 'Single Owner'), ('joint', 'Joint Owner'), ('corporate', 'Corporate')], max_length=20)),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='vehicles/rc/')),
                ('insurance_history', models.FileField(blank=True, null=True, upload_to='vehicles/history/')),
                ('current_mileage', models.IntegerField(default=0)),
                ('is_insured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_policy', 'View Policy'), ('purchase_policy', 'Purchase Policy'), ('file_claim', 'File Claim'), ('update_profile', 'Update Profile'), ('change_password', 'Change Password')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.supportticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_wallet', 'Mobile Wallet'), ('cash', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('payment_details', models.JSONField(default=dict)),
                ('receipt_url', models.URLField(blank=True, max_length=500)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.insurancepolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('claim_update', 'Claim Update'), ('policy_expiry', 'Policy Expiry'), ('payment_confirmation', 'Payment Confirmation'), ('quote_generated', 'Quote Generated'), ('system_alert', 'System Alert'), ('promotion', 'Promotion')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('custom', 'Custom')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('base_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductible', models.DecimalField(decimal_places=2, default=5000, max_digits=12)),
                ('coverage_details', models.JSONField(default=dict)),
                ('add_ons', models.JSONField(default=list)),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.vehicle')),
            ],
            options={
                'db_table': 'insurance_quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='core.vehicle'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('driving_license', 'Driving License'), ('rc', 'Registration Certificate'), ('insurance', 'Insurance Document'), ('claim', 'Claim Document'), ('other', 'Other')], max_length=20)),
                ('document_file', models.FileField(upload_to='documents/')),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('claim_type', models.CharField(choices=[('accident', 'Accident'), ('theft', 'Theft'), ('natural_disaster', 'Natural Disaster'), ('fire', 'Fire'), ('vandalism', 'Vandalism'), ('third_party', 'Third Party')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('settled', 'Settled'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('incident_date', models.DateTimeField()),
                ('incident_location', models.TextField()),
                ('incident_description', models.TextField()),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('documents', models.JSONField(default=list)),
                ('photos', models.JSONField(default=list)),
                ('surveyor_report', models.FileField(blank=True, null=True, upload_to='claims/surveyor_reports/')),
                ('police_report', models.FileField(blank=True, null=True, upload_to='claims/police_reports/')),
                ('surveyor_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_claims', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.insurancepolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user'], name='vehicles_user_id_8632fb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration_number'], name='vehicles_registr_eb8990_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='vehicles_vehicle_d54349_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', '-created_at'], name='user_activi_user_id_543519_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action'], name='user_activi_action_7f2936_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payments_user_id_2c5fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancequote',
            index=models.Index(fields=['user', '-created_at'], name='insurance_q_user_id_69e5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancequote',
            index=models.Index(fields=['status'], name='insurance_q_status_4db3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['user', '-created_at'], name='insurance_p_user_id_7a17b9_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['policy_number'], name='insurance_p_policy__67856c_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['status'], name='insurance_p_status_080899_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['start_date', 'end_date'], name='insurance_p_start_d_ffb76f_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['user', '-created_at'], name='claims_user_id_8451c4_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_number'], name='claims_claim_n_b9e177_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='claims_status_cb731f_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_type'], name='claims_claim_t_dcccb3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='users_is_veri_63cd6e_idx'),
        ),
    ]
