# Generated by Django 5.1.15 on 2026-04-08 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_name_document_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='promocode',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Users'), ('new', 'New Customers Only'), ('existing', 'Existing Customers Only')], default='all', max_length=50),
        ),
        migrations.AddField(
            model_name='promocode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocode',
            name='description',
            field=models.CharField(blank=True, help_text='Description of this promo', max_length=200),
        ),
        migrations.AddField(
            model_name='promocode',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='promocode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='InsuranceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprehensive_multiplier', models.DecimalField(decimal_places=2, default=1.8, help_text='Multiplier for comprehensive coverage (e.g., 1.8 = 180% of base premium)', max_digits=5)),
                ('third_party_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for third party coverage', max_digits=5)),
                ('standalone_multiplier', models.DecimalField(decimal_places=2, default=1.3, help_text='Multiplier for standalone coverage', max_digits=5)),
                ('personal_accident_multiplier', models.DecimalField(decimal_places=2, default=0.6, help_text='Multiplier for personal accident coverage', max_digits=5)),
                ('base_premium_amount', models.DecimalField(decimal_places=2, default=50000.0, help_text='Base premium amount in Naira before multipliers', max_digits=12)),
                ('base_coverage_reference', models.DecimalField(decimal_places=2, default=1000000.0, help_text='Reference coverage amount (1,000,000 Naira) for premium calculation', max_digits=12)),
                ('min_premium_comprehensive', models.DecimalField(decimal_places=2, default=75000.0, max_digits=12)),
                ('min_premium_third_party', models.DecimalField(decimal_places=2, default=15000.0, max_digits=12)),
                ('min_premium_standalone', models.DecimalField(decimal_places=2, default=35000.0, max_digits=12)),
                ('min_premium_personal_accident', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('age_0_1_multiplier', models.DecimalField(decimal_places=2, default=0.9, max_digits=5)),
                ('age_2_3_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('age_4_5_multiplier', models.DecimalField(decimal_places=2, default=1.2, max_digits=5)),
                ('age_6_10_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('age_10_plus_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('car_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('motorcycle_multiplier', models.DecimalField(decimal_places=2, default=0.7, max_digits=5)),
                ('truck_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('bus_multiplier', models.DecimalField(decimal_places=2, default=1.6, max_digits=5)),
                ('rickshaw_multiplier', models.DecimalField(decimal_places=2, default=0.8, max_digits=5)),
                ('engine_above_3000_multiplier', models.DecimalField(decimal_places=2, default=1.3, max_digits=5)),
                ('engine_2000_3000_multiplier', models.DecimalField(decimal_places=2, default=1.15, max_digits=5)),
                ('engine_1000_2000_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('engine_below_1000_multiplier', models.DecimalField(decimal_places=2, default=0.9, max_digits=5)),
                ('deductible_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Deductible as percentage of total premium', max_digits=5)),
                ('min_deductible', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12)),
                ('max_deductible', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12)),
                ('roadside_assistance_cost', models.DecimalField(decimal_places=2, default=15000.0, max_digits=12)),
                ('zero_depreciation_cost', models.DecimalField(decimal_places=2, default=25000.0, max_digits=12)),
                ('engine_protection_cost', models.DecimalField(decimal_places=2, default=20000.0, max_digits=12)),
                ('personal_accident_cover_cost', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('default_promo_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Default discount percentage for new promo codes', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insurance Settings',
                'verbose_name_plural': 'Insurance Settings',
                'db_table': 'insurance_settings',
            },
        ),
    ]
