# Generated by Django 5.1.15 on 2026-04-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_promocode_options_promocode_applicable_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesettings',
            name='bank_account_name',
            field=models.CharField(default='Vehicle Insurance Ltd', max_length=200),
        ),
        migrations.AddField(
            model_name='insurancesettings',
            name='bank_account_number',
            field=models.CharField(default='0123456789', max_length=20),
        ),
        migrations.AddField(
            model_name='insurancesettings',
            name='bank_name',
            field=models.CharField(default='GTBank', max_length=100),
        ),
        migrations.AddField(
            model_name='insurancesettings',
            name='bank_sort_code',
            field=models.CharField(blank=True, default='058123456', max_length=20),
        ),
        migrations.AddField(
            model_name='insurancesettings',
            name='flutterwave_encryption_key',
            field=models.CharField(blank=True, default='xxxxxxxxxxxxx', max_length=200),
        ),
        migrations.AddField(
            model_name='insurancesettings',
            name='flutterwave_is_live',
            field=models.BooleanField(default=False, help_text='Switch to live mode'),
        ),
        migrations.AddField(
            model_name='insurancesettings',
            name='flutterwave_public_key',
            field=models.CharField(blank=True, default='FLWPUBK_TEST-xxxxxxxxxxxxx', max_length=200),
        ),
        migrations.AddField(
            model_name='insurancesettings',
            name='flutterwave_secret_key',
            field=models.CharField(blank=True, default='FLWSECK_TEST-xxxxxxxxxxxxx', max_length=200),
        ),
    ]
