# Generated by Django 5.1.15 on 2026-04-08 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vehicle_created_by_vehicle_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_by',
        ),
    ]
