# Generated by Django 5.1.15 on 2026-04-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogcategory_blogtag_documentcategory_jobcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
