# Generated by Django 5.1.15 on 2026-04-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vehicle_created_by_vehicle_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
