# Generated by Django 5.1.15 on 2026-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesettings',
            name='bank_swift_code',
            field=models.CharField(blank=True, default='ABNGNGLA', max_length=20),
        ),
        migrations.AlterField(
            model_name='insurancesettings',
            name='bank_account_name',
            field=models.CharField(default='VehicleInsure Ltd', max_length=200),
        ),
        migrations.AlterField(
            model_name='insurancesettings',
            name='bank_account_number',
            field=models.CharField(default='0592787269', max_length=20),
        ),
        migrations.AlterField(
            model_name='insurancesettings',
            name='bank_name',
            field=models.CharField(default='Access Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='insurancesettings',
            name='bank_sort_code',
            field=models.CharField(blank=True, default='044152567', max_length=20),
        ),
    ]
