# Generated by Django 5.1.15 on 2026-04-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_insurancesettings_bank_swift_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='auto_debit_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installment',
            name='auto_debit_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='installment',
            name='auto_debit_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='last_auto_debit_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='auto_debit_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='auto_debit_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='card_token',
            field=models.CharField(blank=True, help_text='Tokenized card for recurring payments', max_length=200),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='flutterwave_plan_id',
            field=models.CharField(blank=True, help_text='Flutterwave payment plan ID', max_length=100),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='flutterwave_subscription_id',
            field=models.CharField(blank=True, help_text='Flutterwave subscription ID', max_length=100),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='last_auto_debit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='max_auto_debit_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='next_auto_debit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='payment_mode',
            field=models.CharField(choices=[('manual', 'Manual Payment'), ('auto', 'Automatic Debit')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=15),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['auto_debit_enabled'], name='installment_auto_de_df8889_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['next_auto_debit_date'], name='installment_next_au_140e46_idx'),
        ),
    ]
