# Generated by Django 5.1.15 on 2026-04-09 22:06

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_blogcategory_blogtag_newslettersubscriber_blogpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('publication', models.CharField(help_text='Name of the media outlet', max_length=200)),
                ('publication_logo', models.ImageField(blank=True, null=True, upload_to='press/publications/')),
                ('url', models.URLField(help_text='Link to the article', max_length=500)),
                ('excerpt', models.TextField(max_length=500)),
                ('coverage_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Media Coverage',
                'db_table': 'media_coverage',
                'ordering': ['-coverage_date'],
            },
        ),
        migrations.CreateModel(
            name='MediaKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='press/media_kit/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], max_length=50)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media_kit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PressCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Press Categories',
                'db_table': 'press_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='press/featured/')),
                ('excerpt', models.TextField(help_text='Short summary for press listing', max_length=500)),
                ('content', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of file URLs for attachments')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of image URLs for gallery')),
                ('location', models.CharField(blank=True, help_text='Where the news/event took place', max_length=200)),
                ('press_date', models.DateField(blank=True, help_text='Date of the press release/event', null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('media_contact_name', models.CharField(blank=True, max_length=100)),
                ('media_contact_email', models.EmailField(blank=True, max_length=254)),
                ('media_contact_phone', models.CharField(blank=True, max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_releases', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='core.presscategory')),
            ],
            options={
                'db_table': 'press_releases',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='press_relea_status_f1b87f_idx'), models.Index(fields=['slug'], name='press_relea_slug_bc0b5c_idx'), models.Index(fields=['category'], name='press_relea_categor_8ae708_idx'), models.Index(fields=['is_featured'], name='press_relea_is_feat_dc1ad0_idx')],
            },
        ),
    ]
