# Generated by Django 5.1.15 on 2026-04-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_installment_auto_debit_attempted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_wallet', 'Mobile Wallet'), ('cash', 'Cash'), ('credit_note', 'Credit Note')], max_length=20),
        ),
    ]
