# Generated by Django 5.1.15 on 2026-04-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyendorsement',
            name='effective_date',
            field=models.DateField(help_text='When the changes should take effect'),
        ),
        migrations.AlterField(
            model_name='policyendorsement',
            name='endorsement_type',
            field=models.CharField(choices=[('vehicle_change', 'Vehicle Change'), ('coverage_change', 'Coverage Change'), ('address_change', 'Address Change'), ('name_change', 'Name Change'), ('add_driver', 'Add Driver'), ('remove_driver', 'Remove Driver'), ('sum_insured_change', 'Sum Insured Change'), ('premium_change', 'Premium Adjustment'), ('cancellation', 'Cancellation'), ('reinstatement', 'Reinstatement'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='policyendorsement',
            name='reason',
            field=models.TextField(help_text='Reason for the endorsement request'),
        ),
        migrations.AlterField(
            model_name='policyendorsement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied to Policy'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
