# Generated by Django 5.1.15 on 2026-04-10 01:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jobcategory_joblocation_jobtype_jobposting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='fa-file', max_length=50)),
                ('color', models.CharField(blank=True, default='#4169E1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'db_table': 'document_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublicDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('document_number', models.CharField(blank=True, help_text='Reference number', max_length=100)),
                ('document_type', models.CharField(choices=[('certificate', 'Insurance Certificate'), ('policy', 'Policy Document'), ('receipt', 'Payment Receipt'), ('claim_doc', 'Claim Document'), ('invoice', 'Invoice'), ('renewal', 'Renewal Notice'), ('endorsement', 'Policy Endorsement'), ('other', 'Other')], max_length=20)),
                ('document_file', models.FileField(upload_to='public_documents/')),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('file_extension', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Visible to user in their portal')),
                ('is_verified', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('verification_hash', models.CharField(blank=True, help_text='SHA256 hash for document verification', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_documents', to='core.documentcategory')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_documents', to='core.claim')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_public_documents', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_documents', to='core.payment')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_documents', to='core.insurancepolicy')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_public_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_public_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'public_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('share', 'Share'), ('print', 'Print')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='core.publicdocument')),
            ],
            options={
                'db_table': 'document_access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='publicdocument',
            index=models.Index(fields=['user', '-created_at'], name='public_docu_user_id_94f8f3_idx'),
        ),
        migrations.AddIndex(
            model_name='publicdocument',
            index=models.Index(fields=['document_type'], name='public_docu_documen_8fb98d_idx'),
        ),
        migrations.AddIndex(
            model_name='publicdocument',
            index=models.Index(fields=['status'], name='public_docu_status_369988_idx'),
        ),
        migrations.AddIndex(
            model_name='publicdocument',
            index=models.Index(fields=['policy'], name='public_docu_policy__0cfc71_idx'),
        ),
    ]
