# Generated by Django 5.1.15 on 2026-04-18 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_policyendorsement_effective_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCommissionRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('third_party', 'Third Party'), ('standalone', 'Standalone'), ('personal_accident', 'Personal Accident')], max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_commission_rates',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AgentPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('payment_method', models.CharField(default='bank_transfer', max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_code', models.CharField(max_length=20, unique=True)),
                ('agent_type', models.CharField(choices=[('individual', 'Individual Agent'), ('corporate', 'Corporate Agent'), ('broker', 'Broker')], default='individual', max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_sort_code', models.CharField(blank=True, max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('bonus_eligible', models.BooleanField(default=True)),
                ('total_sales', models.IntegerField(default=0)),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commission_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_month_sales', models.IntegerField(default=0)),
                ('current_month_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_documents', models.JSONField(default=list)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(blank=True, max_length=50)),
                ('referral_source', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=15)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_policies', models.IntegerField(default=0)),
                ('achieved_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('achieved_policies', models.IntegerField(default=0)),
                ('bonus_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_targets',
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='bonus_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[('new_policy', 'New Policy'), ('renewal', 'Policy Renewal'), ('bonus', 'Performance Bonus'), ('override', 'Override Commission')], default='new_policy', max_length=20),
        ),
        migrations.AddField(
            model_name='commission',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent who sold this policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Referral code used during registration', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['agent', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commission',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='core.insurancepolicy'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['commission_type'], name='commissions_commiss_877dc0_idx'),
        ),
        migrations.AddField(
            model_name='agentcommissionrate',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentcommissionrate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentpayout',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentpayout',
            name='commissions',
            field=models.ManyToManyField(related_name='payouts', to='core.commission'),
        ),
        migrations.AddField(
            model_name='agentpayout',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentreferral',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentreferral',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_reference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenttarget',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenttarget',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='agentcommissionrate',
            unique_together={('agent', 'policy_type', 'effective_from')},
        ),
        migrations.AddIndex(
            model_name='agentpayout',
            index=models.Index(fields=['agent', '-created_at'], name='agent_payou_agent_i_2e953e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentpayout',
            index=models.Index(fields=['status'], name='agent_payou_status_b376ab_idx'),
        ),
        migrations.AddIndex(
            model_name='agentpayout',
            index=models.Index(fields=['payout_number'], name='agent_payou_payout__993fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['agent_code'], name='agent_profi_agent_c_25ca0b_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['user'], name='agent_profi_user_id_7d1595_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['is_active'], name='agent_profi_is_acti_b5c3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='agentreferral',
            index=models.Index(fields=['agent'], name='agent_refer_agent_i_6e08ed_idx'),
        ),
        migrations.AddIndex(
            model_name='agentreferral',
            index=models.Index(fields=['customer'], name='agent_refer_custome_ac9058_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agenttarget',
            unique_together={('agent', 'period', 'period_start')},
        ),
    ]
