# Generated by Django 5.1.15 on 2026-04-10 01:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_documentcategory_publicdocument_documentaccesslog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
