# Generated by Django 5.1.15 on 2026-04-18 19:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_agentcommissionrate_agentpayout_agentprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCommissionOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('third_party', 'Third Party'), ('standalone', 'Standalone'), ('personal_accident', 'Personal Accident')], max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_commission_overrides',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AlterModelOptions(
            name='commissionstructure',
            options={'ordering': ['-priority', '-effective_from']},
        ),
        migrations.AlterUniqueTogether(
            name='commissionstructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='bonus_cap',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum bonus amount (0 for unlimited)', max_digits=12),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_structures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='enable_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='enable_tiered_commission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='name',
            field=models.CharField(blank=True, help_text='Structure name for reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority structures are applied first'),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='tier_1_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission rate for tier 1', max_digits=5),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='tier_1_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Premium threshold for tier 1', max_digits=12),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='tier_2_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission rate for tier 2', max_digits=5),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='tier_2_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Premium threshold for tier 2', max_digits=12),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='tier_3_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission rate for tier 3', max_digits=5),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='tier_3_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Premium threshold for tier 3', max_digits=12),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_commission_structures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='agent_type',
            field=models.CharField(choices=[('individual', 'Individual Agent'), ('corporate', 'Corporate Agent'), ('broker', 'Broker'), ('all', 'All Agent Types')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='base_commission_rate',
            field=models.DecimalField(decimal_places=2, help_text='Base commission percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='bonus_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional bonus percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='bonus_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum premium to qualify for bonus', max_digits=12),
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Leave blank for indefinite', null=True),
        ),
        migrations.AddIndex(
            model_name='commissionstructure',
            index=models.Index(fields=['policy_type', 'agent_type'], name='commission__policy__80e998_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionstructure',
            index=models.Index(fields=['is_active'], name='commission__is_acti_423553_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionstructure',
            index=models.Index(fields=['effective_from', 'effective_to'], name='commission__effecti_1fd81d_idx'),
        ),
        migrations.AddField(
            model_name='agentcommissionoverride',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentcommissionoverride',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agentcommissionoverride',
            index=models.Index(fields=['agent', 'policy_type'], name='agent_commi_agent_i_7bbd75_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommissionoverride',
            index=models.Index(fields=['is_active'], name='agent_commi_is_acti_aaf418_idx'),
        ),
    ]
