# Generated by Django 5.1.15 on 2026-04-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_documentcategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
