# Generated by Django 5.1.15 on 2026-04-18 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_agentcommissionoverride_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehicle involved in the claim', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.vehicle'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('accident', 'Accident'), ('theft', 'Theft'), ('natural_disaster', 'Natural Disaster'), ('fire', 'Fire'), ('vandalism', 'Vandalism'), ('third_party', 'Third Party'), ('own_damage', 'Own Damage'), ('windscreen', 'Windscreen'), ('flood', 'Flood'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['vehicle'], name='claims_vehicle_24f04c_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['policy'], name='claims_policy__d2422d_idx'),
        ),
    ]
